[package]
name = "teloren"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = { version = "0.15.8", features = ["serde"] }
termion = "1.5"
clap = "3.1"
specs = { git = "https://github.com/amethyst/specs.git", rev = "d4435bdf496cf322c74886ca09dd8795984919b4" }
tokio = "1"

veloren-client = { git = "https://gitlab.com/veloren/veloren.git", tag = "weekly" }
veloren-common = { git = "https://gitlab.com/veloren/veloren.git", tag = "weekly", features = ["no-assets"] }

[profile.dev]
opt-level = 2
overflow-checks = false
